apiVersion: v1
kind: ServiceAccount
metadata:
  name: Practice-cicd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Practice-cicd
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
      - gateway.kyma-project.io
      - servicecatalog.k8s.io
    resources:
      - deployments
      - replicasets
      - pods
      - jobs
      - configmaps
      - apirules
      - serviceinstances
      - servicebindings
      - services
      - secrets
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Practice-cicd-binding
subjects:
  - kind: ServiceAccount
    name: Practice-cicd
roleRef:
  kind: Role
  name: Practice-cicd
  apiGroup: rbac.authorization.k8s.io